### ISSUE TITLE
 Integrated Wi-Fi chipset's problems

### ISSUE THREAD

**Issue by yuyumiao** [seppzer0/zero_kernel#10]
I can't appoint channel when  i use airodump-ng to monitoring any bssid, terminal shows fix to channel 0,so I can't use aireplay-ng.
Is it chipser's bug or kernel's bug? 
should i buy a External USB wifi card like RTL8812/21AU + RTL8814AU + RTL8187 Wi-Fi drivers;

**Comment by seppzer0** [comment]
> I can't appoint channel when  i use airodump-ng to monitoring any bssid, terminal shows fix to channel 0,so I can't use aireplay-ng.
> Is it chipser's bug or kernel's bug? 

Could you write the kernel build name (.zip file name) and the ROM you're using?

> should i buy a External USB wifi card like RTL8812/21AU + RTL8814AU + RTL8187 Wi-Fi drivers;

Entirely up to you if you want to use an external Wi-Fi adapter; it is unrelated to how the integrated Wi-Fi should work normally by itself.

**Comment by yuyumiao** [comment]
Rom: lineage os 21-20240319-NIGHTLY-dumpling official 
Kernel: 4.4.302-perf+
I use magisk to install nethunter lite and flash your kernel by lineage os official recovery . But it's error excepted when i flash your kernel by lineage OS official recovery
So, I don't know what happened when error excepted.
And i don't know that is your kernel works or I didn't flash it to my device actually.
Maybe I could flash It by TWRP Instead of lineage os official recovery.
At last thank you for this project 🙏

**Comment by yuyumiao** [comment]
![Screenshot_20240408-142257_NetHunter Terminal](https://github.com/seppzer0/zero_kernel/assets/28709983/b1c89e7b-c013-4b01-98e4-6bc38df27dc1)
Its shows on the top of the left,so how cloud I fix it?
or better to buy an external Wi-Fi adapter.

**Comment by seppzer0** [comment]
@yuyumiao , please follow the [instructions](https://github.com/seppzer0/zero_kernel/blob/main/docs/FLASHING.md) to avoid unwanted problems with the Kali NetHunter installation.

I have not used aireplay-ng directly with my device, but I have tested wifite2 on my own networks and it worked as expected.

If you encounter the issue after having followed the flashing+setup instructions, please let me know the commands you used for aireplay-ng (without sensitive infromation such as your network name etc.).

In case the issue remains, I will try to reproduce it and look into it.

**Comment by seppzer0** [comment]
I will be closing this issue as there does not seem to be any follow-up to it.

If you at some point you have any new info towards this, you can always provide it in this issue to get it re-opened.
Until then, the issue will be considered as closed.
