### ISSUE TITLE
Excuse me, does this kernel support docker?

### ISSUE THREAD

**Issue by Xnung** [seppzer0/zero_kernel#13]
If you can support docker, it will be more perfect!

**Comment by seppzer0** [comment]
> If you can support docker, it will be more perfect!

Could you describe a case and it's purposes of how can Docker be used in an Android environment?

**Comment by seppzer0** [comment]
Unfortunately there hasn't been any response with reasoning provided to the issue ticket, which means I will have to close it.

If you decide to provide an update to this topic, feel free to re-open the issue or open a new one.
