### ISSUE TITLE
There is a problem with enabling the external network card

### ISSUE THREAD

**Issue by LuckyFishGeek** [seppzer0/zero_kernel#15]

**Comment by seppzer0** [comment]
@LuckyFishGeek ,

Hi. Yeah, it is a [known issue](https://github.com/seppzer0/s0nh_kernel/blob/main/docs/FAQ.md#q-why-is-there-an-unused-wlan1-interface), which seems to occur on LineageOS builds only, and I have not found a solution for it yet.

This might be related to some of the configurations within LineageOS's defconfig for the kernel. Honestly, not sure about it.
